### PR TITLE
changed the UI new chunkedstream class and some changes to the replication setup

### PR DESCRIPTION
**Pull request by talweiss1982**
commit includes:
1) fixed chunkedstream class
2)changed the replication proxy setup to check if the url is a ravendb one if so it will automaticaly add replication setup if not a connection would still be made but there won't be an attempt to access the url as if it was a ravendb server.
3) changes to the Hed studio to make it lighter:
3.1) "Add Endpoint" it will require you to atleast
add a host url and you may or maynot include a database name.
if one provides database name only that database will be added to the graph.
if one provides only a host than all ravenDB databases on that server would be added as nodes.
Note that the nodes are not saved in the topology until they are connected (they are only added to the UI).
3.2) The behavior select box was left for the user to select the wanted behavior one can use the up/down keys to navigate through behaviors, the selected behavior would reflect on newly created connections.
3.3) Hold Ctrl and click on two nodes to set a connection between them.
3.4) Hold Shift and click on two nodes to remove a connection between them.
3.5) setting a connection between two ravenDB databases will automatically set replication between them in the direction of the connection.

### CODE REVIEW

**Comment by ayende** [comment]
Tal, you need to split work into mulitple commits, that would make it much
easier to review.

*Hibernating Rhinos Ltd  *

Oren Eini\* l CEO l *Mobile: + 972-52-548-6969

Office: +972-4-622-7811 *l *Fax: +972-153-4-622-7811

**Comment by ayende** [comment]
Also, note that you were missing a file GoodChuckedStream.cs (I fixed it,
but please check that the PR compiles properly).

*Hibernating Rhinos Ltd  *

Oren Eini\* l CEO l *Mobile: + 972-52-548-6969

Office: +972-4-622-7811 *l *Fax: +972-153-4-622-7811

On Tue, Dec 2, 2014 at 7:31 PM, Oren Eini (Ayende Rahien) <ayende@ayende.com

**Comment by ayende** [comment]
Also, it doesn't seem to work when I'm trying to run it on my machine.
Let us go over this tomorrow in details.

*Hibernating Rhinos Ltd  *

Oren Eini\* l CEO l *Mobile: + 972-52-548-6969

Office: +972-4-622-7811 *l *Fax: +972-153-4-622-7811

On Tue, Dec 2, 2014 at 7:51 PM, Oren Eini (Ayende Rahien) <ayende@ayende.com

> wrote:
> 
> Also, note that you were missing a file GoodChuckedStream.cs (I fixed it,
> but please check that the PR compiles properly).
> 
> *Hibernating Rhinos Ltd  *
> 
> Oren Eini\* l CEO l *Mobile: + 972-52-548-6969
> 
> Office: +972-4-622-7811 *l *Fax: +972-153-4-622-7811
> 
> On Tue, Dec 2, 2014 at 7:31 PM, Oren Eini (Ayende Rahien) <

**Comment by talweiss1982** [comment]
It is true i should have broken down the commit but i had half cooked stuff
in multiple places.
Regarding the missing file, i have deleted a few files from the VS solution
and it was not picked up by Git (although when adding it does pick those
changes up).
I'm sure we can fix it in a couple of minutes when you get to work.

On Tue, Dec 2, 2014 at 7:56 PM, Ayende Rahien notifications@github.com
wrote:

> Also, it doesn't seem to work when I'm trying to run it on my machine.
> Let us go over this tomorrow in details.
> 
> *Hibernating Rhinos Ltd *
> 
> Oren Eini\* l CEO l *Mobile: + 972-52-548-6969
> 
> Office: +972-4-622-7811 *l *Fax: +972-153-4-622-7811
> 
> On Tue, Dec 2, 2014 at 7:51 PM, Oren Eini (Ayende Rahien) <
> ayende@ayende.com
> 
> > wrote:
> > 
> > Also, note that you were missing a file GoodChuckedStream.cs (I fixed
> > it,
> > but please check that the PR compiles properly).
> > 
> > *Hibernating Rhinos Ltd *
> > 
> > Oren Eini\* l CEO l *Mobile: + 972-52-548-6969
> > 
> > Office: +972-4-622-7811 *l *Fax: +972-153-4-622-7811
> > 
> > On Tue, Dec 2, 2014 at 7:31 PM, Oren Eini (Ayende Rahien) <
> > ayende@ayende.com> wrote:
> > 
> > > Tal, you need to split work into mulitple commits, that would make it
> > > much easier to review.
> > > 
> > > *Hibernating Rhinos Ltd *
> > > 
> > > Oren Eini\* l CEO l *Mobile: + 972-52-548-6969
> > > 
> > > Office: +972-4-622-7811 *l *Fax: +972-153-4-622-7811
> > > 
> > > On Tue, Dec 2, 2014 at 6:11 PM, talweiss1982 notifications@github.com
> > > 
> > > wrote:
> > > 
> > > > commit includes:
> > > > 1) fixed chunkedstream class
> > > > 2)changed the replication proxy setup to check if the url is a ravendb
> > > > one if so it will automaticaly add replication setup if not a
> > > > connection
> > > > would still be made but there won't be an attempt to access the url as
> > > > if
> > > > it was a ravendb server.
> > > > 3) changes to the Hed studio to make it lighter:
> > > > 3.1) "Add Endpoint" it will require you to atleast
> > > > add a host url and you may or maynot include a database name.
> > > > if one provides database name only that database will be added to the
> > > > graph.
> > > > if one provides only a host than all ravenDB databases on that server
> > > > would be added as nodes.
> > > > Note that the nodes are not saved in the topology until they are
> > > > connected (they are only added to the UI).
> > > > 3.2) The behavior select box was left for the user to select the
> > > > wanted
> > > > behavior one can use the up/down keys to navigate through behaviors,
> > > > the
> > > > selected behavior would reflect on newly created connections.
> > > > 3.3) Hold Ctrl and click on two nodes to set a connection between
> > > > them.
> > > > 3.4) Hold Shift and click on two nodes to remove a connection between
> > > > them.
> > > > 3.5) setting a connection between two ravenDB databases will
> > > > automatically set replication between them in the direction of the
> > > > 
> > > > ## connection.
> > > > 
> > > > You can merge this Pull Request by running
> > > > 
> > > > git pull https://github.com/talweiss1982/Hed master
> > > > 
> > > > Or view, comment on, or merge it at:
> > > > 
> > > > https://github.com/ayende/Hed/pull/4
> > > > Commit Summary
> > > > - changed the UI of Hed studio with some minor changes to
> > > >   ReplicationProxySetup
> > > > 
> > > > File Changes
> > > > - _M_ Hed.Server/Hed.Server.csproj
> > > >   https://github.com/ayende/Hed/pull/4/files#diff-0 (1)
> > > > - _M_ Hed.Server/Utils/ChunkedStream.cs
> > > >   https://github.com/ayende/Hed/pull/4/files#diff-1 (246)
> > > > - _M_ Hed.Studio/App/Models/connection.js
> > > >   https://github.com/ayende/Hed/pull/4/files#diff-2 (4)
> > > > - _M_ Hed.Studio/App/Models/connection.js.map
> > > >   https://github.com/ayende/Hed/pull/4/files#diff-3 (2)
> > > > - _M_ Hed.Studio/App/Models/connection.ts
> > > >   https://github.com/ayende/Hed/pull/4/files#diff-4 (4)
> > > > - _D_ Hed.Studio/App/Models/requestStatistics.js
> > > >   https://github.com/ayende/Hed/pull/4/files#diff-5 (48)
> > > > - _D_ Hed.Studio/App/Models/requestStatistics.js.map
> > > >   https://github.com/ayende/Hed/pull/4/files#diff-6 (1)
> > > > - _D_ Hed.Studio/App/Models/requestStatistics.ts
> > > >   https://github.com/ayende/Hed/pull/4/files#diff-7 (45)
> > > > - _M_ Hed.Studio/App/Viewmodels/homeViewModel.js
> > > >   https://github.com/ayende/Hed/pull/4/files#diff-8 (215)
> > > > - _M_ Hed.Studio/App/Viewmodels/homeViewModel.js.map
> > > >   https://github.com/ayende/Hed/pull/4/files#diff-9 (2)
> > > > - _M_ Hed.Studio/App/Viewmodels/homeViewModel.ts
> > > >   https://github.com/ayende/Hed/pull/4/files#diff-10 (228)
> > > > - _M_ Hed.Studio/Content/app.css
> > > >   https://github.com/ayende/Hed/pull/4/files#diff-11 (19)
> > > > - _M_ Hed.Studio/Content/app.css.map
> > > >   https://github.com/ayende/Hed/pull/4/files#diff-12 (2)
> > > > - _M_ Hed.Studio/Content/app.less
> > > >   https://github.com/ayende/Hed/pull/4/files#diff-13 (21)
> > > > - _M_ Hed.Studio/Content/app.min.css
> > > >   https://github.com/ayende/Hed/pull/4/files#diff-14 (2)
> > > > - _M_ Hed.Studio/Hed.Studio.csproj
> > > >   https://github.com/ayende/Hed/pull/4/files#diff-15 (11)
> > > > - _A_ Hed.Studio/Scripts/d3.d.ts
> > > >   https://github.com/ayende/Hed/pull/4/files#diff-16 (3451)
> > > > - _D_ Hed.Studio/Scripts/dracula_algorithms.js
> > > >   https://github.com/ayende/Hed/pull/4/files#diff-17 (599)
> > > > - _D_ Hed.Studio/Scripts/dracula_graffle.js
> > > >   https://github.com/ayende/Hed/pull/4/files#diff-18 (113)
> > > > - _D_ Hed.Studio/Scripts/dracula_graph.js
> > > >   https://github.com/ayende/Hed/pull/4/files#diff-19 (527)
> > > > - _D_ Hed.Studio/Scripts/example.js
> > > >   https://github.com/ayende/Hed/pull/4/files#diff-20 (115)
> > > > - _A_ Hed.Studio/Scripts/nvd3.d.ts
> > > >   https://github.com/ayende/Hed/pull/4/files#diff-21 (6)
> > > > - _D_ Hed.Studio/Scripts/raphael-min.js
> > > >   https://github.com/ayende/Hed/pull/4/files#diff-22 (7)
> > > > - _A_ Hed.Studio/Scripts/timelines.d.ts
> > > >   https://github.com/ayende/Hed/pull/4/files#diff-23 (3)
> > > > - _A_ Hed.Studio/Scripts/timelinesChart.d.ts
> > > >   https://github.com/ayende/Hed/pull/4/files#diff-24 (3)
> > > > - _M_ Hed.Studio/index.html
> > > >   https://github.com/ayende/Hed/pull/4/files#diff-25 (53)
> > > > - _A_ Hed.Studio/lib/dagred3.js
> > > >   https://github.com/ayende/Hed/pull/4/files#diff-26 (2)
> > > > - _A_ Hed.Studio/lib/dagred3.js.map
> > > >   https://github.com/ayende/Hed/pull/4/files#diff-27 (1)
> > > > - _A_ Hed.Studio/lib/dagred3.ts
> > > >   https://github.com/ayende/Hed/pull/4/files#diff-28 (1)
> > > > - _D_ Samples/Hed.ConsoleHost/Controllers/ReplicationController.cs
> > > >   https://github.com/ayende/Hed/pull/4/files#diff-29 (21)
> > > > - _M_ Samples/Hed.ConsoleHost/Controllers/TopologyController.cs
> > > >   https://github.com/ayende/Hed/pull/4/files#diff-30 (47)
> > > > - _M_ Samples/Hed.ConsoleHost/DocumentStoreFactory.cs
> > > >   https://github.com/ayende/Hed/pull/4/files#diff-31 (2)
> > > > - _M_ Samples/Hed.ConsoleHost/Hed.ConsoleHost.csproj
> > > >   https://github.com/ayende/Hed/pull/4/files#diff-32 (1)
> > > > - _M_ Samples/Hed.ConsoleHost/HedConfiguration.cs
> > > >   https://github.com/ayende/Hed/pull/4/files#diff-33 (4)
> > > > - _M_ Samples/Hed.ConsoleHost/Program.cs
> > > >   https://github.com/ayende/Hed/pull/4/files#diff-34 (14)
> > > > - _M_ Samples/Hed.ConsoleHost/ReplicationProxySetup.cs
> > > >   https://github.com/ayende/Hed/pull/4/files#diff-35 (80)
> > > > 
> > > > Patch Links:
> > > > - https://github.com/ayende/Hed/pull/4.patch
> > > > - https://github.com/ayende/Hed/pull/4.diff
> > > > 
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > https://github.com/ayende/Hed/pull/4.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ayende/Hed/pull/4#issuecomment-65273860.

## 

*Hibernating Rhinos Ltd  *[image: cid:image001.png@01CF95E2.8ED1B7D0]

Tal Weiss\* l **Core Team Developer l *Mobile:+972-54-802-4849

Office: +972-4-622-7811\* l *Fax: +972-153-4-622-7811

**Pull request merged**
